#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_CURVE_EDITOR_MAIN                   101
#define IDD_CURVE_EDITOR_CURVE                  103
#define IDR_FONT_BMP                            106
#define IDR_FONT_DAT                            107
#define IDD_SH_LIGHT_EDITOR_MAIN                110
#define IDC_PROPERTY_EDITX1                     1000
#define IDC_CURVE_EDITOR_MAIN_NAME              1003
#define IDC_CURVE_EDITOR_MAIN_TYPE              1005
#define IDC_CURVE_EDITOR_MAIN_FORMAT            1007
#define IDC_CURVE_EDITOR_MAIN_X_CURVE           1009
#define IDC_CURVE_EDITOR_MAIN_Y_CURVE           1013
#define IDC_CURVE_EDITOR_MAIN_Z_CURVE           1014
#define IDC_CURVE_EDITOR_MAIN_W_CURVE           1015
#define IDC_CURVE_EDITOR_MAIN_EDIT_X_CURVE      1017
#define IDC_CURVE_EDITOR_MAIN_EDIT_Y_CURVE      1019
#define IDC_CURVE_EDITOR_MAIN_EDIT_Z_CURVE      1021
#define IDC_CURVE_EDITOR_MAIN_EDIT_W_CURVE      1023
#define IDC_CURVE_EDITOR_MAIN_CURVES_TREE       1024
#define IDC_CURVE_EDITOR_CURVE_HELP_GROUPBOX    1025
#define IDC_CURVE_EDITOR_CURVE_HELP_STATIC      1026
#define IDC_CURVE_EDITOR_CURVE_ACTIONS_GROUPBOX 1028
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_1_STATIC 1029
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_1_EDITBOX 1031
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_2_STATIC 1033
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_2_EDITBOX 1035
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_3_STATIC 1037
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_3_EDITBOX 1039
#define IDC_CURVE_EDITOR_CURVE_VIEW             1040
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_4_EDITBOX 1042
#define IDC_CURVE_EDITOR_CURVE_PROPERTY_4_STATIC 1044
#define IDC_PROPERTY_NAME1                      1047
#define IDC_PROPERTY_NAME2                      1049
#define IDC_PROPERTY_NAME3                      1051
#define IDC_PROPERTY_NAME4                      1053
#define IDC_PROPERTY_NAME5                      1055
#define IDC_PROPERTY_NAME6                      1057
#define IDC_PROPERTY_NAME7                      1059
#define IDC_PROPERTY_NAME8                      1061
#define IDC_SH_LIGHT_PROJECTIONS                1064
#define IDC_PROPERTY_EDITY1                     1067
#define IDC_PROPERTY_EDITZ1                     1069
#define IDC_PROPERTY_EDITW1                     1071
#define IDC_PROPERTY_EDITY2                     1072
#define IDC_PROPERTY_EDITZ2                     1073
#define IDC_PROPERTY_EDITW2                     1074
#define IDC_PROPERTY_EDITX2                     1075
#define IDC_PROPERTY_EDITX3                     1076
#define IDC_PROPERTY_EDITY3                     1077
#define IDC_PROPERTY_EDITZ3                     1078
#define IDC_PROPERTY_EDITW3                     1079
#define IDC_PROPERTY_EDITX4                     1080
#define IDC_PROPERTY_EDITY4                     1081
#define IDC_PROPERTY_EDITZ4                     1082
#define IDC_PROPERTY_EDITW4                     1083
#define IDC_PROPERTY_EDITW5                     1084
#define IDC_PROPERTY_EDITX5                     1085
#define IDC_PROPERTY_EDITY5                     1086
#define IDC_PROPERTY_EDITZ5                     1087
#define IDC_PROPERTY_EDITX6                     1088
#define IDC_PROPERTY_EDITY6                     1089
#define IDC_PROPERTY_EDITZ6                     1090
#define IDC_PROPERTY_EDITW6                     1091
#define IDC_PROPERTY_EDITX7                     1092
#define IDC_PROPERTY_EDITY7                     1093
#define IDC_PROPERTY_EDITZ7                     1094
#define IDC_PROPERTY_EDITW7                     1095
#define IDC_PROPERTY_EDITX8                     1096
#define IDC_PROPERTY_EDITY8                     1097
#define IDC_PROPERTY_EDITW8                     1098
#define IDC_PROPERTY_EDITZ8                     1099
