/**
 *
 * Emerald (kbi/elude @2012)
 *
 * Holds font table as exported by Bitmap Font Generated by Codehead (what?). Okay, the tool
 * might have a stupid name, but it's free for both freeware and commercial purposes and does
 * its job, so deal with it :)
 *
 * The font table requires to files to work:
 *
 * - dat file (which contains info on font sizes)
 * - bmp file
 *
 * Both of these files can be exported using the tool.
 */
#ifndef GFX_BFG_BONT_TABLE_H
#define GFX_BFG_BONT_TABLE_H

#include "gfx/gfx_types.h"

REFCOUNT_INSERT_DECLARATIONS(gfx_bfg_font_table, gfx_bfg_font_table)


/******************** EXPORTED *****************************/
/** TODO. font_table_file_name without extension! */
PUBLIC EMERALD_API gfx_bfg_font_table gfx_bfg_font_table_create(system_hashed_ansi_string font_table_file_name);

/** TODO */
PUBLIC EMERALD_API gfx_bfg_font_table gfx_bfg_font_table_create_from_ptr(system_hashed_ansi_string name,
                                                                         void*                     bmp_blob,
                                                                         void*                     dat_blob);

/** TODO.
 *
 *  @return true if character is present in the map, false otherwise.
 **/
PUBLIC EMERALD_API bool gfx_bfg_font_table_get_character_properties(gfx_bfg_font_table,
                                                                    uint8_t /* ascii index */,
                                                                    float* /* u1 */,
                                                                    float* /* v1 */,
                                                                    float* /* u2 */,
                                                                    float* /* v2 */);

/** TODO */
PUBLIC EMERALD_API bool gfx_bfg_font_table_get_character_size(gfx_bfg_font_table,
                                                              uint8_t  /* ascii index */,
                                                              uint8_t* /* out width */,
                                                              uint8_t* /* out height */);

/** TODO */
PUBLIC EMERALD_API const unsigned char* gfx_bfg_font_table_get_data_pointer(gfx_bfg_font_table);

/** TODO */
PUBLIC EMERALD_API void gfx_bfg_font_table_get_data_properties(gfx_bfg_font_table,
                                                               uint32_t* /* map width */,
                                                               uint32_t* /* map height */);

/** TODO */
PUBLIC EMERALD_API uint8_t gfx_bfg_font_table_get_maximum_character_height(gfx_bfg_font_table);

/** TODO */
PUBLIC EMERALD_API uint8_t gfx_bfg_font_table_get_maximum_character_width(gfx_bfg_font_table);

#endif /* GFX_BFG_BONT_TABLE_H */
